AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  normalizador:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: ''
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue:
              'Fn::GetAtt':
                - SQSQueue1
                - Arn
            BatchSize: 1
      VpcConfig:
        SecurityGroupIds:
          - 
        SubnetIds:
          - 
      Environment:
        Variables:
          dbname: dev
          host:
          password:
          port:
          user: 
      Layers:
        - ''
  SQSQueue1:
    Type: 'AWS::SQS::Queue'
    Properties: {}
